services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
